/****************************************************************************
**
** Namespace TrueConf_CallXLib generated by dumpcpp v5.9.1 using
** C:\Qt\Qt5.9.1\5.9.1\msvc2015\bin\dumpcpp {b5d60cbd-e7f7-4d70-959b-bd14068436a5}
** from the type library C:\Program Files (x86)\TrueConf\CallX\TrueConf_CallX.ocx
**
****************************************************************************/

#ifndef QAX_DUMPCPP_TRUECONF_CALLXLIB_H
#define QAX_DUMPCPP_TRUECONF_CALLXLIB_H

// Define this symbol to __declspec(dllexport) or __declspec(dllimport)
#ifndef TRUECONF_CALLXLIB_EXPORT
#define TRUECONF_CALLXLIB_EXPORT
#endif

#include <qaxobject.h>
#include <qaxwidget.h>
#include <qdatetime.h>
#include <qpixmap.h>

struct IDispatch;


// Referenced namespace

namespace TrueConf_CallXLib {


// skipping event interface _ITrueConfCallXEvents

class TRUECONF_CALLXLIB_EXPORT ITrueConfCallX : public QAxObject
{
public:
    ITrueConfCallX(IDispatch *subobject = 0, QAxObject *parent = 0)
    : QAxObject((IUnknown*)subobject, parent)
    {
        internalRelease();
    }

    /*
    Property CallXPath

    full path to Trueconf CallX application

    */
    inline QString CallXPath() const; //Returns the value of CallXPath
    inline void SetCallXPath(const QString& value); //Sets the value of the CallXPath property

    /*
    Property Camera
    */
    inline QString Camera() const; //Returns the value of Camera
    inline void SetCamera(const QString& value); //Sets the value of the Camera property

    /*
    Property Microphone
    */
    inline QString Microphone() const; //Returns the value of Microphone
    inline void SetMicrophone(const QString& value); //Sets the value of the Microphone property

    /*
    Property Speaker
    */
    inline QString Speaker() const; //Returns the value of Speaker
    inline void SetSpeaker(const QString& value); //Sets the value of the Speaker property

    /*
    Property XCommandLine
    */
    inline QString XCommandLine() const; //Returns the value of XCommandLine
    inline void SetXCommandLine(const QString& value); //Sets the value of the XCommandLine property

    /*
    Method XAddSlide
    */
    inline void XAddSlide(const QString& imgPath);

    /*
    Method XAddSlidesDialog
    */
    inline uint XAddSlidesDialog();

    /*
    Method XCheckForEvent

    Check event-specification of notification data

    */
    inline bool XCheckForEvent(const QString& notificationData, const QString& eventName);

    /*
    Method XDeselectCamera
    */
    inline void XDeselectCamera();

    /*
    Method XDeselectMic
    */
    inline void XDeselectMic();

    /*
    Method XDeselectSpeaker
    */
    inline void XDeselectSpeaker();

    /*
    Method XEncryptedLogin
    */
    inline void XEncryptedLogin(const QString& login, const QString& password, bool encryptPassword);

    /*
    Method XExecuteCommand

    Execute script command

    */
    inline void XExecuteCommand(const QString& cmd);

    /*
    Method XFileAccept
    */
    inline bool XFileAccept(int fileId);

    /*
    Method XFileDelete
    */
    inline bool XFileDelete(int fileId);

    /*
    Method XFileReject
    */
    inline bool XFileReject(int fileId);

    /*
    Method XFileSend
    */
    inline int XFileSend(const QString& peerId, const QString& filePath, const QString& fileCaption);

    /*
    Method XFileSendAbort
    */
    inline bool XFileSendAbort(int fileId);

    /*
    Method XFileSendToConference
    */
    inline int XFileSendToConference(const QString& filePath, const QString& fileCaption);

    /*
    Method XFileStatsInfo
    */
    inline bool XFileStatsInfo(int fileId, int& size, int& downloaded, int& uploaded, int& u_speed, int& d_speed, int& peers);

    /*
    Method XFileTransferAvailable
    */
    inline bool XFileTransferAvailable();

    /*
    Method XForceRestart
    */
    inline void XForceRestart();

    /*
    Method XGetCallXProcessId
    */
    inline int XGetCallXProcessId();

    /*
    Method XGetCameraByIndex
    */
    inline QString XGetCameraByIndex(int cameraIdx);

    /*
    Method XGetCameraCount
    */
    inline int XGetCameraCount();

    /*
    Method XGetCameraList
    */
    inline QString XGetCameraList();

    /*
    Method XGetFileDownloadPath
    */
    inline QString XGetFileDownloadPath(int fileId);

    /*
    Method XGetFileHashById
    */
    inline QString XGetFileHashById(int fileId);

    /*
    Method XGetFileIdByHash
    */
    inline int XGetFileIdByHash(const QString& hash);

    /*
    Method XGetFileSendStatus
    */
    inline int XGetFileSendStatus(int id);

    /*
    Method XGetFileTransferList
    */
    inline QString XGetFileTransferList();

    /*
    Method XGetHandle
    */
    inline uint XGetHandle();

    /*
    Method XGetMicByIndex
    */
    inline QString XGetMicByIndex(int microphoneIdx);

    /*
    Method XGetMicCount
    */
    inline int XGetMicCount();

    /*
    Method XGetMicList
    */
    inline QString XGetMicList();

    /*
    Method XGetSpeakerByIndex
    */
    inline QString XGetSpeakerByIndex(int speakerIdx);

    /*
    Method XGetSpeakerCount
    */
    inline int XGetSpeakerCount();

    /*
    Method XGetSpeakerList
    */
    inline QString XGetSpeakerList();

    /*
    Method XHangUpForAll
    */
    inline void XHangUpForAll();

    /*
    Method XPrintPdf
    */
    inline int XPrintPdf(const QString& filePath);

    /*
    Method XRemotePrintPdf
    */
    inline int XRemotePrintPdf(const QString& peerId, int fileId);

    /*
    Method XRemoveSlide
    */
    inline void XRemoveSlide(int imgIdx);

    /*
    Method XRestart

    restart Terminal instance

    */
    inline void XRestart();

    /*
    Method XSelectCamera
    */
    inline void XSelectCamera(const QString& cameraName);

    /*
    Method XSelectMicByIndex
    */
    inline void XSelectMicByIndex(int microphoneIdx);

    /*
    Method XSelectSpeakerByIndex
    */
    inline void XSelectSpeakerByIndex(int speakerIdx);

    /*
    Method XSetBackgroundImage
    */
    inline void XSetBackgroundImage(const QString& imgPath);

    /*
    Method XSetCameraByIndex
    */
    inline void XSetCameraByIndex(int cameraIdx);

    /*
    Method XStartPictureBroadcast
    */
    inline void XStartPictureBroadcast(const QString& imgPath);

    /*
    Method XStopPictureBroadcast
    */
    inline void XStopPictureBroadcast();

    /*
    Method accept
    */
    inline void accept();

    /*
    Method acceptPeer
    */
    inline void acceptPeer(const QString& peerId);

    /*
    Method acceptPodiumInvite
    */
    inline void acceptPodiumInvite();

    /*
    Method acceptPodiumRequest
    */
    inline void acceptPodiumRequest();

    /*
    Method acceptPodiumRequest2
    */
    inline void acceptPodiumRequest2(const QString& peerId);

    /*
    Method activateLicense
    */
    inline void activateLicense(const QString& licenseKey);

    /*
    Method addContactToAbook
    */
    inline void addContactToAbook(const QString& callId, const QString& displayName);

    /*
    Method addToAbook
    */
    inline QString addToAbook(const QString& peerId, const QString& displayName);

    /*
    Method addToGroup
    */
    inline QString addToGroup(int groupId, const QString& peerId);

    /*
    Method allowRecord
    */
    inline void allowRecord();

    /*
    Method allowRecord2
    */
    inline void allowRecord2(const QString& peerId);

    /*
    Method appUpdate
    */
    inline void appUpdate();

    /*
    Method block
    */
    inline QString block(const QString& peerId);

    /*
    Method call
    */
    inline void call(const QString& peerId);

    /*
    Method changeVideoMatrix
    */
    inline void changeVideoMatrix(const QString& jsonMatrix);

    /*
    Method chatClear
    */
    inline QString chatClear(const QString& chatId);

    /*
    Method clearSlides
    */
    inline void clearSlides();

    /*
    Method connectToServer
    */
    inline void connectToServer(const QString& serverStr);

    /*
    Method createConference
    */
    inline void createConference(const QString& confName, const QString& type, bool autoAccept, const QString& users);

    /*
    Method createGroup
    */
    inline QString createGroup(const QString& name);

    /*
    Method extendUidTtl
    */
    inline void extendUidTtl();

    /*
    Method firstSlide
    */
    inline void firstSlide();

    /*
    Method forbidRecord
    */
    inline void forbidRecord();

    /*
    Method forbidRecord2
    */
    inline void forbidRecord2(const QString& peerId);

    /*
    Method getAbook
    */
    inline void getAbook();

    /*
    Method getAppState
    */
    inline void getAppState();

    /*
    Method getAudioMute
    */
    inline void getAudioMute();

    /*
    Method getBanList
    */
    inline QString getBanList();

    /*
    Method getCallHistory
    */
    inline QString getCallHistory(int count);

    /*
    Method getChatLastMessages
    */
    inline QString getChatLastMessages(const QString& chatId, int count);

    /*
    Method getContactDetails
    */
    inline void getContactDetails(const QString& peerId);

    /*
    Method getDisplayNameById
    */
    inline void getDisplayNameById(const QString& peerId);

    /*
    Method getGroups
    */
    inline QString getGroups();

    /*
    Method getHardware
    */
    inline void getHardware();

    /*
    Method getHardwareKey
    */
    inline void getHardwareKey();

    /*
    Method getIdListRequestInvite
    */
    inline void getIdListRequestInvite();

    /*
    Method getLicenseType
    */
    inline void getLicenseType();

    /*
    Method getListOfChats
    */
    inline QString getListOfChats();

    /*
    Method getMaxConfTitleLength
    */
    inline void getMaxConfTitleLength();

    /*
    Method getMicMute
    */
    inline void getMicMute();

    /*
    Method getModes
    */
    inline void getModes();

    /*
    Method getMonitorsInfo
    */
    inline void getMonitorsInfo();

    /*
    Method getParticipantsList
    */
    inline QString getParticipantsList();

    /*
    Method getSelfieBroadcast
    */
    inline void getSelfieBroadcast();

    /*
    Method getSettings
    */
    inline void getSettings();

    /*
    Method getSlideShowInfo
    */
    inline void getSlideShowInfo();

    /*
    Method getSystemInfo
    */
    inline void getSystemInfo();

    /*
    Method getVideoMatrix
    */
    inline void getVideoMatrix();

    /*
    Method getVideoMute
    */
    inline void getVideoMute();

    /*
    Method gotoPodium
    */
    inline void gotoPodium();

    /*
    Method hangUp
    */
    inline void hangUp();

    /*
    Method hangUp2
    */
    inline void hangUp2(bool forAll);

    /*
    Method inviteToConference
    */
    inline void inviteToConference(const QString& peerId);

    /*
    Method inviteToPodium
    */
    inline void inviteToPodium(const QString& peerId);

    /*
    Method lastSlide
    */
    inline void lastSlide();

    /*
    Method leavePodium
    */
    inline void leavePodium();

    /*
    Method login
    */
    inline void login(const QString& login, const QString& password);

    /*
    Method logout
    */
    inline void logout();

    /*
    Method moveSlideDown
    */
    inline void moveSlideDown(int slideIdx);

    /*
    Method moveSlideUp
    */
    inline void moveSlideUp(int slideIdx);

    /*
    Method nextSlide
    */
    inline void nextSlide();

    /*
    Method prevSlide
    */
    inline void prevSlide();

    /*
    Method ptzDown
    */
    inline void ptzDown();

    /*
    Method ptzLeft
    */
    inline void ptzLeft();

    /*
    Method ptzRight
    */
    inline void ptzRight();

    /*
    Method ptzStop
    */
    inline void ptzStop();

    /*
    Method ptzUp
    */
    inline void ptzUp();

    /*
    Method ptzZoomIn
    */
    inline void ptzZoomIn();

    /*
    Method ptzZoomOut
    */
    inline void ptzZoomOut();

    /*
    Method reject
    */
    inline void reject();

    /*
    Method rejectInvitationToPodium
    */
    inline void rejectInvitationToPodium();

    /*
    Method rejectPeer
    */
    inline void rejectPeer(const QString& peerId);

    /*
    Method rejectRequestToPodium
    */
    inline void rejectRequestToPodium();

    /*
    Method rejectRequestToPodium2
    */
    inline void rejectRequestToPodium2(const QString& peerId);

    /*
    Method removeContactFromAbook
    */
    inline void removeContactFromAbook(const QString& callId);

    /*
    Method removeFromAbook
    */
    inline QString removeFromAbook(const QString& peerId);

    /*
    Method removeFromGroup
    */
    inline QString removeFromGroup(int groupId, const QString& peerId);

    /*
    Method removeFromPodium
    */
    inline void removeFromPodium(const QString& peerId);

    /*
    Method removeGroup
    */
    inline QString removeGroup(int groupId);

    /*
    Method removePeer
    */
    inline void removePeer(const QString& peerId);

    /*
    Method renameGroup
    */
    inline QString renameGroup(int groupId, const QString& newGroupName);

    /*
    Method renameInAbook
    */
    inline QString renameInAbook(const QString& peerId, const QString& newDisplayName);

    /*
    Method sendCommand
    */
    inline void sendCommand(const QString& peerId, const QString& cmd);

    /*
    Method sendGroupMessage
    */
    inline QString sendGroupMessage(const QString& message);

    /*
    Method sendMessage
    */
    inline QString sendMessage(const QString& peerId, const QString& message);

    /*
    Method setAudioMute
    */
    inline void setAudioMute(bool mute);

    /*
    Method setHardware
    */
    inline void setHardware(const QString& hardwareInJson);

    /*
    Method setLastCallsViewed
    */
    inline QString setLastCallsViewed();

    /*
    Method setMicMute
    */
    inline void setMicMute(bool mute);

    /*
    Method setModes
    */
    inline void setModes(const QString& pin, const QString& mode);

    /*
    Method setSelfieBroadcast
    */
    inline void setSelfieBroadcast(const QString& paramsInJSON);

    /*
    Method setSettings
    */
    inline void setSettings(const QString& settingsInJson);

    /*
    Method setVideoMute
    */
    inline void setVideoMute(bool mute);

    /*
    Method showSlide
    */
    inline void showSlide(int slideIdx);

    /*
    Method shutdown
    */
    inline void shutdown();

    /*
    Method shutdown2
    */
    inline void shutdown2(bool forAll);

    /*
    Method startAudioRemark
    */
    inline void startAudioRemark();

    /*
    Method startScreenCapture
    */
    inline void startScreenCapture(const QString& id);

    /*
    Method startSlideShow
    */
    inline void startSlideShow(const QString& slideShowName);

    /*
    Method stopScreenCapture
    */
    inline void stopScreenCapture();

    /*
    Method stopSlideShow
    */
    inline void stopSlideShow();

    /*
    Method switchVideoStream
    */
    inline void switchVideoStream(const QString& peerId, bool mainCamera);

    /*
    Method takePicture
    */
    inline void takePicture(const QString& outputFileName);

    /*
    Method testAudioCapturerStart
    */
    inline QString testAudioCapturerStart();

    /*
    Method testAudioCapturerStop
    */
    inline QString testAudioCapturerStop();

    /*
    Method testAudioRenderer
    */
    inline QString testAudioRenderer();

    /*
    Method toneDial
    */
    inline QString toneDial(const QString& symbol);

    /*
    Method turnRemoteCamera
    */
    inline void turnRemoteCamera(const QString& peerId, bool on);

    /*
    Method turnRemoteMic
    */
    inline void turnRemoteMic(const QString& peerId, bool on);

    /*
    Method unblock
    */
    inline QString unblock(const QString& peerId);

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// Actual coclasses
class TRUECONF_CALLXLIB_EXPORT TrueConfCallX : public QAxWidget
{
public:
    TrueConfCallX(QWidget *parent = 0, Qt::WindowFlags f = 0)
    : QAxWidget(parent, f)
    {
        setControl(QStringLiteral("{27ef4ba2-4500-4839-b88a-f2f4744fe56a}"));
    }

    TrueConfCallX(ITrueConfCallX *iface)
    : QAxWidget()
    {
        initializeFrom(iface);
        delete iface;
    }

    /*
    Property CallXPath

    full path to Trueconf CallX application

    */
    inline QString CallXPath() const; //Returns the value of CallXPath
    inline void SetCallXPath(const QString& value); //Sets the value of the CallXPath property

    /*
    Property Camera
    */
    inline QString Camera() const; //Returns the value of Camera
    inline void SetCamera(const QString& value); //Sets the value of the Camera property

    /*
    Property Microphone
    */
    inline QString Microphone() const; //Returns the value of Microphone
    inline void SetMicrophone(const QString& value); //Sets the value of the Microphone property

    /*
    Property Speaker
    */
    inline QString Speaker() const; //Returns the value of Speaker
    inline void SetSpeaker(const QString& value); //Sets the value of the Speaker property

    /*
    Property XCommandLine
    */
    inline QString XCommandLine() const; //Returns the value of XCommandLine
    inline void SetXCommandLine(const QString& value); //Sets the value of the XCommandLine property

    /*
    Method XAddSlide
    */
    inline void XAddSlide(const QString& imgPath);

    /*
    Method XAddSlidesDialog
    */
    inline uint XAddSlidesDialog();

    /*
    Method XCheckForEvent

    Check event-specification of notification data

    */
    inline bool XCheckForEvent(const QString& notificationData, const QString& eventName);

    /*
    Method XDeselectCamera
    */
    inline void XDeselectCamera();

    /*
    Method XDeselectMic
    */
    inline void XDeselectMic();

    /*
    Method XDeselectSpeaker
    */
    inline void XDeselectSpeaker();

    /*
    Method XEncryptedLogin
    */
    inline void XEncryptedLogin(const QString& login, const QString& password, bool encryptPassword);

    /*
    Method XExecuteCommand

    Execute script command

    */
    inline void XExecuteCommand(const QString& cmd);

    /*
    Method XFileAccept
    */
    inline bool XFileAccept(int fileId);

    /*
    Method XFileDelete
    */
    inline bool XFileDelete(int fileId);

    /*
    Method XFileReject
    */
    inline bool XFileReject(int fileId);

    /*
    Method XFileSend
    */
    inline int XFileSend(const QString& peerId, const QString& filePath, const QString& fileCaption);

    /*
    Method XFileSendAbort
    */
    inline bool XFileSendAbort(int fileId);

    /*
    Method XFileSendToConference
    */
    inline int XFileSendToConference(const QString& filePath, const QString& fileCaption);

    /*
    Method XFileStatsInfo
    */
    inline bool XFileStatsInfo(int fileId, int& size, int& downloaded, int& uploaded, int& u_speed, int& d_speed, int& peers);

    /*
    Method XFileTransferAvailable
    */
    inline bool XFileTransferAvailable();

    /*
    Method XForceRestart
    */
    inline void XForceRestart();

    /*
    Method XGetCallXProcessId
    */
    inline int XGetCallXProcessId();

    /*
    Method XGetCameraByIndex
    */
    inline QString XGetCameraByIndex(int cameraIdx);

    /*
    Method XGetCameraCount
    */
    inline int XGetCameraCount();

    /*
    Method XGetCameraList
    */
    inline QString XGetCameraList();

    /*
    Method XGetFileDownloadPath
    */
    inline QString XGetFileDownloadPath(int fileId);

    /*
    Method XGetFileHashById
    */
    inline QString XGetFileHashById(int fileId);

    /*
    Method XGetFileIdByHash
    */
    inline int XGetFileIdByHash(const QString& hash);

    /*
    Method XGetFileSendStatus
    */
    inline int XGetFileSendStatus(int id);

    /*
    Method XGetFileTransferList
    */
    inline QString XGetFileTransferList();

    /*
    Method XGetHandle
    */
    inline uint XGetHandle();

    /*
    Method XGetMicByIndex
    */
    inline QString XGetMicByIndex(int microphoneIdx);

    /*
    Method XGetMicCount
    */
    inline int XGetMicCount();

    /*
    Method XGetMicList
    */
    inline QString XGetMicList();

    /*
    Method XGetSpeakerByIndex
    */
    inline QString XGetSpeakerByIndex(int speakerIdx);

    /*
    Method XGetSpeakerCount
    */
    inline int XGetSpeakerCount();

    /*
    Method XGetSpeakerList
    */
    inline QString XGetSpeakerList();

    /*
    Method XHangUpForAll
    */
    inline void XHangUpForAll();

    /*
    Method XPrintPdf
    */
    inline int XPrintPdf(const QString& filePath);

    /*
    Method XRemotePrintPdf
    */
    inline int XRemotePrintPdf(const QString& peerId, int fileId);

    /*
    Method XRemoveSlide
    */
    inline void XRemoveSlide(int imgIdx);

    /*
    Method XRestart

    restart Terminal instance

    */
    inline void XRestart();

    /*
    Method XSelectCamera
    */
    inline void XSelectCamera(const QString& cameraName);

    /*
    Method XSelectMicByIndex
    */
    inline void XSelectMicByIndex(int microphoneIdx);

    /*
    Method XSelectSpeakerByIndex
    */
    inline void XSelectSpeakerByIndex(int speakerIdx);

    /*
    Method XSetBackgroundImage
    */
    inline void XSetBackgroundImage(const QString& imgPath);

    /*
    Method XSetCameraByIndex
    */
    inline void XSetCameraByIndex(int cameraIdx);

    /*
    Method XStartPictureBroadcast
    */
    inline void XStartPictureBroadcast(const QString& imgPath);

    /*
    Method XStopPictureBroadcast
    */
    inline void XStopPictureBroadcast();

    /*
    Method accept
    */
    inline void accept();

    /*
    Method acceptPeer
    */
    inline void acceptPeer(const QString& peerId);

    /*
    Method acceptPodiumInvite
    */
    inline void acceptPodiumInvite();

    /*
    Method acceptPodiumRequest
    */
    inline void acceptPodiumRequest();

    /*
    Method acceptPodiumRequest2
    */
    inline void acceptPodiumRequest2(const QString& peerId);

    /*
    Method activateLicense
    */
    inline void activateLicense(const QString& licenseKey);

    /*
    Method addContactToAbook
    */
    inline void addContactToAbook(const QString& callId, const QString& displayName);

    /*
    Method addToAbook
    */
    inline QString addToAbook(const QString& peerId, const QString& displayName);

    /*
    Method addToGroup
    */
    inline QString addToGroup(int groupId, const QString& peerId);

    /*
    Method allowRecord
    */
    inline void allowRecord();

    /*
    Method allowRecord2
    */
    inline void allowRecord2(const QString& peerId);

    /*
    Method appUpdate
    */
    inline void appUpdate();

    /*
    Method block
    */
    inline QString block(const QString& peerId);

    /*
    Method call
    */
    inline void call(const QString& peerId);

    /*
    Method changeVideoMatrix
    */
    inline void changeVideoMatrix(const QString& jsonMatrix);

    /*
    Method chatClear
    */
    inline QString chatClear(const QString& chatId);

    /*
    Method clearSlides
    */
    inline void clearSlides();

    /*
    Method connectToServer
    */
    inline void connectToServer(const QString& serverStr);

    /*
    Method createConference
    */
    inline void createConference(const QString& confName, const QString& type, bool autoAccept, const QString& users);

    /*
    Method createGroup
    */
    inline QString createGroup(const QString& name);

    /*
    Method extendUidTtl
    */
    inline void extendUidTtl();

    /*
    Method firstSlide
    */
    inline void firstSlide();

    /*
    Method forbidRecord
    */
    inline void forbidRecord();

    /*
    Method forbidRecord2
    */
    inline void forbidRecord2(const QString& peerId);

    /*
    Method getAbook
    */
    inline void getAbook();

    /*
    Method getAppState
    */
    inline void getAppState();

    /*
    Method getAudioMute
    */
    inline void getAudioMute();

    /*
    Method getBanList
    */
    inline QString getBanList();

    /*
    Method getCallHistory
    */
    inline QString getCallHistory(int count);

    /*
    Method getChatLastMessages
    */
    inline QString getChatLastMessages(const QString& chatId, int count);

    /*
    Method getContactDetails
    */
    inline void getContactDetails(const QString& peerId);

    /*
    Method getDisplayNameById
    */
    inline void getDisplayNameById(const QString& peerId);

    /*
    Method getGroups
    */
    inline QString getGroups();

    /*
    Method getHardware
    */
    inline void getHardware();

    /*
    Method getHardwareKey
    */
    inline void getHardwareKey();

    /*
    Method getIdListRequestInvite
    */
    inline void getIdListRequestInvite();

    /*
    Method getLicenseType
    */
    inline void getLicenseType();

    /*
    Method getListOfChats
    */
    inline QString getListOfChats();

    /*
    Method getMaxConfTitleLength
    */
    inline void getMaxConfTitleLength();

    /*
    Method getMicMute
    */
    inline void getMicMute();

    /*
    Method getModes
    */
    inline void getModes();

    /*
    Method getMonitorsInfo
    */
    inline void getMonitorsInfo();

    /*
    Method getParticipantsList
    */
    inline QString getParticipantsList();

    /*
    Method getSelfieBroadcast
    */
    inline void getSelfieBroadcast();

    /*
    Method getSettings
    */
    inline void getSettings();

    /*
    Method getSlideShowInfo
    */
    inline void getSlideShowInfo();

    /*
    Method getSystemInfo
    */
    inline void getSystemInfo();

    /*
    Method getVideoMatrix
    */
    inline void getVideoMatrix();

    /*
    Method getVideoMute
    */
    inline void getVideoMute();

    /*
    Method gotoPodium
    */
    inline void gotoPodium();

    /*
    Method hangUp
    */
    inline void hangUp();

    /*
    Method hangUp2
    */
    inline void hangUp2(bool forAll);

    /*
    Method inviteToConference
    */
    inline void inviteToConference(const QString& peerId);

    /*
    Method inviteToPodium
    */
    inline void inviteToPodium(const QString& peerId);

    /*
    Method lastSlide
    */
    inline void lastSlide();

    /*
    Method leavePodium
    */
    inline void leavePodium();

    /*
    Method login
    */
    inline void login(const QString& login, const QString& password);

    /*
    Method logout
    */
    inline void logout();

    /*
    Method moveSlideDown
    */
    inline void moveSlideDown(int slideIdx);

    /*
    Method moveSlideUp
    */
    inline void moveSlideUp(int slideIdx);

    /*
    Method nextSlide
    */
    inline void nextSlide();

    /*
    Method prevSlide
    */
    inline void prevSlide();

    /*
    Method ptzDown
    */
    inline void ptzDown();

    /*
    Method ptzLeft
    */
    inline void ptzLeft();

    /*
    Method ptzRight
    */
    inline void ptzRight();

    /*
    Method ptzStop
    */
    inline void ptzStop();

    /*
    Method ptzUp
    */
    inline void ptzUp();

    /*
    Method ptzZoomIn
    */
    inline void ptzZoomIn();

    /*
    Method ptzZoomOut
    */
    inline void ptzZoomOut();

    /*
    Method reject
    */
    inline void reject();

    /*
    Method rejectInvitationToPodium
    */
    inline void rejectInvitationToPodium();

    /*
    Method rejectPeer
    */
    inline void rejectPeer(const QString& peerId);

    /*
    Method rejectRequestToPodium
    */
    inline void rejectRequestToPodium();

    /*
    Method rejectRequestToPodium2
    */
    inline void rejectRequestToPodium2(const QString& peerId);

    /*
    Method removeContactFromAbook
    */
    inline void removeContactFromAbook(const QString& callId);

    /*
    Method removeFromAbook
    */
    inline QString removeFromAbook(const QString& peerId);

    /*
    Method removeFromGroup
    */
    inline QString removeFromGroup(int groupId, const QString& peerId);

    /*
    Method removeFromPodium
    */
    inline void removeFromPodium(const QString& peerId);

    /*
    Method removeGroup
    */
    inline QString removeGroup(int groupId);

    /*
    Method removePeer
    */
    inline void removePeer(const QString& peerId);

    /*
    Method renameGroup
    */
    inline QString renameGroup(int groupId, const QString& newGroupName);

    /*
    Method renameInAbook
    */
    inline QString renameInAbook(const QString& peerId, const QString& newDisplayName);

    /*
    Method sendCommand
    */
    inline void sendCommand(const QString& peerId, const QString& cmd);

    /*
    Method sendGroupMessage
    */
    inline QString sendGroupMessage(const QString& message);

    /*
    Method sendMessage
    */
    inline QString sendMessage(const QString& peerId, const QString& message);

    /*
    Method setAudioMute
    */
    inline void setAudioMute(bool mute);

    /*
    Method setHardware
    */
    inline void setHardware(const QString& hardwareInJson);

    /*
    Method setLastCallsViewed
    */
    inline QString setLastCallsViewed();

    /*
    Method setMicMute
    */
    inline void setMicMute(bool mute);

    /*
    Method setModes
    */
    inline void setModes(const QString& pin, const QString& mode);

    /*
    Method setSelfieBroadcast
    */
    inline void setSelfieBroadcast(const QString& paramsInJSON);

    /*
    Method setSettings
    */
    inline void setSettings(const QString& settingsInJson);

    /*
    Method setVideoMute
    */
    inline void setVideoMute(bool mute);

    /*
    Method showSlide
    */
    inline void showSlide(int slideIdx);

    /*
    Method shutdown
    */
    inline void shutdown();

    /*
    Method shutdown2
    */
    inline void shutdown2(bool forAll);

    /*
    Method startAudioRemark
    */
    inline void startAudioRemark();

    /*
    Method startScreenCapture
    */
    inline void startScreenCapture(const QString& id);

    /*
    Method startSlideShow
    */
    inline void startSlideShow(const QString& slideShowName);

    /*
    Method stopScreenCapture
    */
    inline void stopScreenCapture();

    /*
    Method stopSlideShow
    */
    inline void stopSlideShow();

    /*
    Method switchVideoStream
    */
    inline void switchVideoStream(const QString& peerId, bool mainCamera);

    /*
    Method takePicture
    */
    inline void takePicture(const QString& outputFileName);

    /*
    Method testAudioCapturerStart
    */
    inline QString testAudioCapturerStart();

    /*
    Method testAudioCapturerStop
    */
    inline QString testAudioCapturerStop();

    /*
    Method testAudioRenderer
    */
    inline QString testAudioRenderer();

    /*
    Method toneDial
    */
    inline QString toneDial(const QString& symbol);

    /*
    Method turnRemoteCamera
    */
    inline void turnRemoteCamera(const QString& peerId, bool on);

    /*
    Method turnRemoteMic
    */
    inline void turnRemoteMic(const QString& peerId, bool on);

    /*
    Method unblock
    */
    inline QString unblock(const QString& peerId);

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// member function implementation
#ifndef QAX_DUMPCPP_TRUECONF_CALLXLIB_NOINLINES
inline QString TrueConfCallX::CallXPath() const
{
    QVariant qax_result = property("CallXPath");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void TrueConfCallX::SetCallXPath(const QString& value){ setProperty("CallXPath", QVariant(value)); }

inline QString TrueConfCallX::Camera() const
{
    QVariant qax_result = property("Camera");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void TrueConfCallX::SetCamera(const QString& value){ setProperty("Camera", QVariant(value)); }

inline QString TrueConfCallX::Microphone() const
{
    QVariant qax_result = property("Microphone");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void TrueConfCallX::SetMicrophone(const QString& value){ setProperty("Microphone", QVariant(value)); }

inline QString TrueConfCallX::Speaker() const
{
    QVariant qax_result = property("Speaker");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void TrueConfCallX::SetSpeaker(const QString& value){ setProperty("Speaker", QVariant(value)); }

inline QString TrueConfCallX::XCommandLine() const
{
    QVariant qax_result = property("XCommandLine");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void TrueConfCallX::SetXCommandLine(const QString& value){ setProperty("XCommandLine", QVariant(value)); }

inline void TrueConfCallX::XAddSlide(const QString& imgPath)
{
    void *_a[] = {0, (void*)&imgPath};
    qt_metacall(QMetaObject::InvokeMetaMethod, 126, _a);
}

inline uint TrueConfCallX::XAddSlidesDialog()
{
    uint qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 127, _a);
    return qax_result;
}

inline bool TrueConfCallX::XCheckForEvent(const QString& notificationData, const QString& eventName)
{
    bool qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&notificationData, (void*)&eventName};
    qt_metacall(QMetaObject::InvokeMetaMethod, 128, _a);
    return qax_result;
}

inline void TrueConfCallX::XDeselectCamera()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 129, _a);
}

inline void TrueConfCallX::XDeselectMic()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 130, _a);
}

inline void TrueConfCallX::XDeselectSpeaker()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 131, _a);
}

inline void TrueConfCallX::XEncryptedLogin(const QString& login, const QString& password, bool encryptPassword)
{
    void *_a[] = {0, (void*)&login, (void*)&password, (void*)&encryptPassword};
    qt_metacall(QMetaObject::InvokeMetaMethod, 132, _a);
}

inline void TrueConfCallX::XExecuteCommand(const QString& cmd)
{
    void *_a[] = {0, (void*)&cmd};
    qt_metacall(QMetaObject::InvokeMetaMethod, 133, _a);
}

inline bool TrueConfCallX::XFileAccept(int fileId)
{
    bool qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&fileId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 134, _a);
    return qax_result;
}

inline bool TrueConfCallX::XFileDelete(int fileId)
{
    bool qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&fileId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 135, _a);
    return qax_result;
}

inline bool TrueConfCallX::XFileReject(int fileId)
{
    bool qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&fileId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 136, _a);
    return qax_result;
}

inline int TrueConfCallX::XFileSend(const QString& peerId, const QString& filePath, const QString& fileCaption)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&peerId, (void*)&filePath, (void*)&fileCaption};
    qt_metacall(QMetaObject::InvokeMetaMethod, 137, _a);
    return qax_result;
}

inline bool TrueConfCallX::XFileSendAbort(int fileId)
{
    bool qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&fileId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 138, _a);
    return qax_result;
}

inline int TrueConfCallX::XFileSendToConference(const QString& filePath, const QString& fileCaption)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&filePath, (void*)&fileCaption};
    qt_metacall(QMetaObject::InvokeMetaMethod, 139, _a);
    return qax_result;
}

inline bool TrueConfCallX::XFileStatsInfo(int fileId, int& size, int& downloaded, int& uploaded, int& u_speed, int& d_speed, int& peers)
{
    bool qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&fileId, (void*)&size, (void*)&downloaded, (void*)&uploaded, (void*)&u_speed, (void*)&d_speed, (void*)&peers};
    qt_metacall(QMetaObject::InvokeMetaMethod, 140, _a);
    return qax_result;
}

inline bool TrueConfCallX::XFileTransferAvailable()
{
    bool qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 141, _a);
    return qax_result;
}

inline void TrueConfCallX::XForceRestart()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 142, _a);
}

inline int TrueConfCallX::XGetCallXProcessId()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 143, _a);
    return qax_result;
}

inline QString TrueConfCallX::XGetCameraByIndex(int cameraIdx)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&cameraIdx};
    qt_metacall(QMetaObject::InvokeMetaMethod, 144, _a);
    return qax_result;
}

inline int TrueConfCallX::XGetCameraCount()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 145, _a);
    return qax_result;
}

inline QString TrueConfCallX::XGetCameraList()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 146, _a);
    return qax_result;
}

inline QString TrueConfCallX::XGetFileDownloadPath(int fileId)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&fileId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 147, _a);
    return qax_result;
}

inline QString TrueConfCallX::XGetFileHashById(int fileId)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&fileId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 148, _a);
    return qax_result;
}

inline int TrueConfCallX::XGetFileIdByHash(const QString& hash)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&hash};
    qt_metacall(QMetaObject::InvokeMetaMethod, 149, _a);
    return qax_result;
}

inline int TrueConfCallX::XGetFileSendStatus(int id)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&id};
    qt_metacall(QMetaObject::InvokeMetaMethod, 150, _a);
    return qax_result;
}

inline QString TrueConfCallX::XGetFileTransferList()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 151, _a);
    return qax_result;
}

inline uint TrueConfCallX::XGetHandle()
{
    uint qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 152, _a);
    return qax_result;
}

inline QString TrueConfCallX::XGetMicByIndex(int microphoneIdx)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&microphoneIdx};
    qt_metacall(QMetaObject::InvokeMetaMethod, 153, _a);
    return qax_result;
}

inline int TrueConfCallX::XGetMicCount()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 154, _a);
    return qax_result;
}

inline QString TrueConfCallX::XGetMicList()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 155, _a);
    return qax_result;
}

inline QString TrueConfCallX::XGetSpeakerByIndex(int speakerIdx)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&speakerIdx};
    qt_metacall(QMetaObject::InvokeMetaMethod, 156, _a);
    return qax_result;
}

inline int TrueConfCallX::XGetSpeakerCount()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 157, _a);
    return qax_result;
}

inline QString TrueConfCallX::XGetSpeakerList()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 158, _a);
    return qax_result;
}

inline void TrueConfCallX::XHangUpForAll()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 159, _a);
}

inline int TrueConfCallX::XPrintPdf(const QString& filePath)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&filePath};
    qt_metacall(QMetaObject::InvokeMetaMethod, 160, _a);
    return qax_result;
}

inline int TrueConfCallX::XRemotePrintPdf(const QString& peerId, int fileId)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&peerId, (void*)&fileId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 161, _a);
    return qax_result;
}

inline void TrueConfCallX::XRemoveSlide(int imgIdx)
{
    void *_a[] = {0, (void*)&imgIdx};
    qt_metacall(QMetaObject::InvokeMetaMethod, 162, _a);
}

inline void TrueConfCallX::XRestart()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 163, _a);
}

inline void TrueConfCallX::XSelectCamera(const QString& cameraName)
{
    void *_a[] = {0, (void*)&cameraName};
    qt_metacall(QMetaObject::InvokeMetaMethod, 164, _a);
}

inline void TrueConfCallX::XSelectMicByIndex(int microphoneIdx)
{
    void *_a[] = {0, (void*)&microphoneIdx};
    qt_metacall(QMetaObject::InvokeMetaMethod, 165, _a);
}

inline void TrueConfCallX::XSelectSpeakerByIndex(int speakerIdx)
{
    void *_a[] = {0, (void*)&speakerIdx};
    qt_metacall(QMetaObject::InvokeMetaMethod, 166, _a);
}

inline void TrueConfCallX::XSetBackgroundImage(const QString& imgPath)
{
    void *_a[] = {0, (void*)&imgPath};
    qt_metacall(QMetaObject::InvokeMetaMethod, 167, _a);
}

inline void TrueConfCallX::XSetCameraByIndex(int cameraIdx)
{
    void *_a[] = {0, (void*)&cameraIdx};
    qt_metacall(QMetaObject::InvokeMetaMethod, 168, _a);
}

inline void TrueConfCallX::XStartPictureBroadcast(const QString& imgPath)
{
    void *_a[] = {0, (void*)&imgPath};
    qt_metacall(QMetaObject::InvokeMetaMethod, 169, _a);
}

inline void TrueConfCallX::XStopPictureBroadcast()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 170, _a);
}

inline void TrueConfCallX::accept()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 171, _a);
}

inline void TrueConfCallX::acceptPeer(const QString& peerId)
{
    void *_a[] = {0, (void*)&peerId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 172, _a);
}

inline void TrueConfCallX::acceptPodiumInvite()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 173, _a);
}

inline void TrueConfCallX::acceptPodiumRequest()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 174, _a);
}

inline void TrueConfCallX::acceptPodiumRequest2(const QString& peerId)
{
    void *_a[] = {0, (void*)&peerId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 175, _a);
}

inline void TrueConfCallX::activateLicense(const QString& licenseKey)
{
    void *_a[] = {0, (void*)&licenseKey};
    qt_metacall(QMetaObject::InvokeMetaMethod, 176, _a);
}

inline void TrueConfCallX::addContactToAbook(const QString& callId, const QString& displayName)
{
    void *_a[] = {0, (void*)&callId, (void*)&displayName};
    qt_metacall(QMetaObject::InvokeMetaMethod, 177, _a);
}

inline QString TrueConfCallX::addToAbook(const QString& peerId, const QString& displayName)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&peerId, (void*)&displayName};
    qt_metacall(QMetaObject::InvokeMetaMethod, 178, _a);
    return qax_result;
}

inline QString TrueConfCallX::addToGroup(int groupId, const QString& peerId)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&groupId, (void*)&peerId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 179, _a);
    return qax_result;
}

inline void TrueConfCallX::allowRecord()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 180, _a);
}

inline void TrueConfCallX::allowRecord2(const QString& peerId)
{
    void *_a[] = {0, (void*)&peerId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 181, _a);
}

inline void TrueConfCallX::appUpdate()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 182, _a);
}

inline QString TrueConfCallX::block(const QString& peerId)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&peerId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 183, _a);
    return qax_result;
}

inline void TrueConfCallX::call(const QString& peerId)
{
    void *_a[] = {0, (void*)&peerId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 184, _a);
}

inline void TrueConfCallX::changeVideoMatrix(const QString& jsonMatrix)
{
    void *_a[] = {0, (void*)&jsonMatrix};
    qt_metacall(QMetaObject::InvokeMetaMethod, 185, _a);
}

inline QString TrueConfCallX::chatClear(const QString& chatId)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&chatId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 186, _a);
    return qax_result;
}

inline void TrueConfCallX::clearSlides()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 187, _a);
}

inline void TrueConfCallX::connectToServer(const QString& serverStr)
{
    void *_a[] = {0, (void*)&serverStr};
    qt_metacall(QMetaObject::InvokeMetaMethod, 188, _a);
}

inline void TrueConfCallX::createConference(const QString& confName, const QString& type, bool autoAccept, const QString& users)
{
    void *_a[] = {0, (void*)&confName, (void*)&type, (void*)&autoAccept, (void*)&users};
    qt_metacall(QMetaObject::InvokeMetaMethod, 189, _a);
}

inline QString TrueConfCallX::createGroup(const QString& name)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&name};
    qt_metacall(QMetaObject::InvokeMetaMethod, 190, _a);
    return qax_result;
}

inline void TrueConfCallX::extendUidTtl()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 191, _a);
}

inline void TrueConfCallX::firstSlide()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 192, _a);
}

inline void TrueConfCallX::forbidRecord()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 193, _a);
}

inline void TrueConfCallX::forbidRecord2(const QString& peerId)
{
    void *_a[] = {0, (void*)&peerId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 194, _a);
}

inline void TrueConfCallX::getAbook()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 195, _a);
}

inline void TrueConfCallX::getAppState()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 196, _a);
}

inline void TrueConfCallX::getAudioMute()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 197, _a);
}

inline QString TrueConfCallX::getBanList()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 198, _a);
    return qax_result;
}

inline QString TrueConfCallX::getCallHistory(int count)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&count};
    qt_metacall(QMetaObject::InvokeMetaMethod, 199, _a);
    return qax_result;
}

inline QString TrueConfCallX::getChatLastMessages(const QString& chatId, int count)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&chatId, (void*)&count};
    qt_metacall(QMetaObject::InvokeMetaMethod, 200, _a);
    return qax_result;
}

inline void TrueConfCallX::getContactDetails(const QString& peerId)
{
    void *_a[] = {0, (void*)&peerId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 201, _a);
}

inline void TrueConfCallX::getDisplayNameById(const QString& peerId)
{
    void *_a[] = {0, (void*)&peerId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 202, _a);
}

inline QString TrueConfCallX::getGroups()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 203, _a);
    return qax_result;
}

inline void TrueConfCallX::getHardware()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 204, _a);
}

inline void TrueConfCallX::getHardwareKey()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 205, _a);
}

inline void TrueConfCallX::getIdListRequestInvite()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 206, _a);
}

inline void TrueConfCallX::getLicenseType()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 207, _a);
}

inline QString TrueConfCallX::getListOfChats()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 208, _a);
    return qax_result;
}

inline void TrueConfCallX::getMaxConfTitleLength()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 209, _a);
}

inline void TrueConfCallX::getMicMute()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 210, _a);
}

inline void TrueConfCallX::getModes()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 211, _a);
}

inline void TrueConfCallX::getMonitorsInfo()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 212, _a);
}

inline QString TrueConfCallX::getParticipantsList()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 213, _a);
    return qax_result;
}

inline void TrueConfCallX::getSelfieBroadcast()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 214, _a);
}

inline void TrueConfCallX::getSettings()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 215, _a);
}

inline void TrueConfCallX::getSlideShowInfo()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 216, _a);
}

inline void TrueConfCallX::getSystemInfo()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 217, _a);
}

inline void TrueConfCallX::getVideoMatrix()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 218, _a);
}

inline void TrueConfCallX::getVideoMute()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 219, _a);
}

inline void TrueConfCallX::gotoPodium()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 220, _a);
}

inline void TrueConfCallX::hangUp()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 221, _a);
}

inline void TrueConfCallX::hangUp2(bool forAll)
{
    void *_a[] = {0, (void*)&forAll};
    qt_metacall(QMetaObject::InvokeMetaMethod, 222, _a);
}

inline void TrueConfCallX::inviteToConference(const QString& peerId)
{
    void *_a[] = {0, (void*)&peerId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 223, _a);
}

inline void TrueConfCallX::inviteToPodium(const QString& peerId)
{
    void *_a[] = {0, (void*)&peerId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 224, _a);
}

inline void TrueConfCallX::lastSlide()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 225, _a);
}

inline void TrueConfCallX::leavePodium()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 226, _a);
}

inline void TrueConfCallX::login(const QString& login, const QString& password)
{
    void *_a[] = {0, (void*)&login, (void*)&password};
    qt_metacall(QMetaObject::InvokeMetaMethod, 227, _a);
}

inline void TrueConfCallX::logout()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 228, _a);
}

inline void TrueConfCallX::moveSlideDown(int slideIdx)
{
    void *_a[] = {0, (void*)&slideIdx};
    qt_metacall(QMetaObject::InvokeMetaMethod, 229, _a);
}

inline void TrueConfCallX::moveSlideUp(int slideIdx)
{
    void *_a[] = {0, (void*)&slideIdx};
    qt_metacall(QMetaObject::InvokeMetaMethod, 230, _a);
}

inline void TrueConfCallX::nextSlide()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 231, _a);
}

inline void TrueConfCallX::prevSlide()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 232, _a);
}

inline void TrueConfCallX::ptzDown()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 233, _a);
}

inline void TrueConfCallX::ptzLeft()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 234, _a);
}

inline void TrueConfCallX::ptzRight()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 235, _a);
}

inline void TrueConfCallX::ptzStop()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 236, _a);
}

inline void TrueConfCallX::ptzUp()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 237, _a);
}

inline void TrueConfCallX::ptzZoomIn()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 238, _a);
}

inline void TrueConfCallX::ptzZoomOut()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 239, _a);
}

inline void TrueConfCallX::reject()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 240, _a);
}

inline void TrueConfCallX::rejectInvitationToPodium()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 241, _a);
}

inline void TrueConfCallX::rejectPeer(const QString& peerId)
{
    void *_a[] = {0, (void*)&peerId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 242, _a);
}

inline void TrueConfCallX::rejectRequestToPodium()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 243, _a);
}

inline void TrueConfCallX::rejectRequestToPodium2(const QString& peerId)
{
    void *_a[] = {0, (void*)&peerId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 244, _a);
}

inline void TrueConfCallX::removeContactFromAbook(const QString& callId)
{
    void *_a[] = {0, (void*)&callId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 245, _a);
}

inline QString TrueConfCallX::removeFromAbook(const QString& peerId)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&peerId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 246, _a);
    return qax_result;
}

inline QString TrueConfCallX::removeFromGroup(int groupId, const QString& peerId)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&groupId, (void*)&peerId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 247, _a);
    return qax_result;
}

inline void TrueConfCallX::removeFromPodium(const QString& peerId)
{
    void *_a[] = {0, (void*)&peerId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 248, _a);
}

inline QString TrueConfCallX::removeGroup(int groupId)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&groupId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 249, _a);
    return qax_result;
}

inline void TrueConfCallX::removePeer(const QString& peerId)
{
    void *_a[] = {0, (void*)&peerId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 250, _a);
}

inline QString TrueConfCallX::renameGroup(int groupId, const QString& newGroupName)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&groupId, (void*)&newGroupName};
    qt_metacall(QMetaObject::InvokeMetaMethod, 251, _a);
    return qax_result;
}

inline QString TrueConfCallX::renameInAbook(const QString& peerId, const QString& newDisplayName)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&peerId, (void*)&newDisplayName};
    qt_metacall(QMetaObject::InvokeMetaMethod, 252, _a);
    return qax_result;
}

inline void TrueConfCallX::sendCommand(const QString& peerId, const QString& cmd)
{
    void *_a[] = {0, (void*)&peerId, (void*)&cmd};
    qt_metacall(QMetaObject::InvokeMetaMethod, 253, _a);
}

inline QString TrueConfCallX::sendGroupMessage(const QString& message)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&message};
    qt_metacall(QMetaObject::InvokeMetaMethod, 254, _a);
    return qax_result;
}

inline QString TrueConfCallX::sendMessage(const QString& peerId, const QString& message)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&peerId, (void*)&message};
    qt_metacall(QMetaObject::InvokeMetaMethod, 255, _a);
    return qax_result;
}

inline void TrueConfCallX::setAudioMute(bool mute)
{
    void *_a[] = {0, (void*)&mute};
    qt_metacall(QMetaObject::InvokeMetaMethod, 256, _a);
}

inline void TrueConfCallX::setHardware(const QString& hardwareInJson)
{
    void *_a[] = {0, (void*)&hardwareInJson};
    qt_metacall(QMetaObject::InvokeMetaMethod, 257, _a);
}

inline QString TrueConfCallX::setLastCallsViewed()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 258, _a);
    return qax_result;
}

inline void TrueConfCallX::setMicMute(bool mute)
{
    void *_a[] = {0, (void*)&mute};
    qt_metacall(QMetaObject::InvokeMetaMethod, 259, _a);
}

inline void TrueConfCallX::setModes(const QString& pin, const QString& mode)
{
    void *_a[] = {0, (void*)&pin, (void*)&mode};
    qt_metacall(QMetaObject::InvokeMetaMethod, 260, _a);
}

inline void TrueConfCallX::setSelfieBroadcast(const QString& paramsInJSON)
{
    void *_a[] = {0, (void*)&paramsInJSON};
    qt_metacall(QMetaObject::InvokeMetaMethod, 261, _a);
}

inline void TrueConfCallX::setSettings(const QString& settingsInJson)
{
    void *_a[] = {0, (void*)&settingsInJson};
    qt_metacall(QMetaObject::InvokeMetaMethod, 262, _a);
}

inline void TrueConfCallX::setVideoMute(bool mute)
{
    void *_a[] = {0, (void*)&mute};
    qt_metacall(QMetaObject::InvokeMetaMethod, 263, _a);
}

inline void TrueConfCallX::showSlide(int slideIdx)
{
    void *_a[] = {0, (void*)&slideIdx};
    qt_metacall(QMetaObject::InvokeMetaMethod, 264, _a);
}

inline void TrueConfCallX::shutdown()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 265, _a);
}

inline void TrueConfCallX::shutdown2(bool forAll)
{
    void *_a[] = {0, (void*)&forAll};
    qt_metacall(QMetaObject::InvokeMetaMethod, 266, _a);
}

inline void TrueConfCallX::startAudioRemark()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 267, _a);
}

inline void TrueConfCallX::startScreenCapture(const QString& id)
{
    void *_a[] = {0, (void*)&id};
    qt_metacall(QMetaObject::InvokeMetaMethod, 268, _a);
}

inline void TrueConfCallX::startSlideShow(const QString& slideShowName)
{
    void *_a[] = {0, (void*)&slideShowName};
    qt_metacall(QMetaObject::InvokeMetaMethod, 269, _a);
}

inline void TrueConfCallX::stopScreenCapture()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 270, _a);
}

inline void TrueConfCallX::stopSlideShow()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 271, _a);
}

inline void TrueConfCallX::switchVideoStream(const QString& peerId, bool mainCamera)
{
    void *_a[] = {0, (void*)&peerId, (void*)&mainCamera};
    qt_metacall(QMetaObject::InvokeMetaMethod, 272, _a);
}

inline void TrueConfCallX::takePicture(const QString& outputFileName)
{
    void *_a[] = {0, (void*)&outputFileName};
    qt_metacall(QMetaObject::InvokeMetaMethod, 273, _a);
}

inline QString TrueConfCallX::testAudioCapturerStart()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 274, _a);
    return qax_result;
}

inline QString TrueConfCallX::testAudioCapturerStop()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 275, _a);
    return qax_result;
}

inline QString TrueConfCallX::testAudioRenderer()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 276, _a);
    return qax_result;
}

inline QString TrueConfCallX::toneDial(const QString& symbol)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&symbol};
    qt_metacall(QMetaObject::InvokeMetaMethod, 277, _a);
    return qax_result;
}

inline void TrueConfCallX::turnRemoteCamera(const QString& peerId, bool on)
{
    void *_a[] = {0, (void*)&peerId, (void*)&on};
    qt_metacall(QMetaObject::InvokeMetaMethod, 278, _a);
}

inline void TrueConfCallX::turnRemoteMic(const QString& peerId, bool on)
{
    void *_a[] = {0, (void*)&peerId, (void*)&on};
    qt_metacall(QMetaObject::InvokeMetaMethod, 279, _a);
}

inline QString TrueConfCallX::unblock(const QString& peerId)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&peerId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 280, _a);
    return qax_result;
}


inline QString ITrueConfCallX::CallXPath() const
{
    QVariant qax_result = property("CallXPath");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void ITrueConfCallX::SetCallXPath(const QString& value){ setProperty("CallXPath", QVariant(value)); }

inline QString ITrueConfCallX::Camera() const
{
    QVariant qax_result = property("Camera");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void ITrueConfCallX::SetCamera(const QString& value){ setProperty("Camera", QVariant(value)); }

inline QString ITrueConfCallX::Microphone() const
{
    QVariant qax_result = property("Microphone");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void ITrueConfCallX::SetMicrophone(const QString& value){ setProperty("Microphone", QVariant(value)); }

inline QString ITrueConfCallX::Speaker() const
{
    QVariant qax_result = property("Speaker");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void ITrueConfCallX::SetSpeaker(const QString& value){ setProperty("Speaker", QVariant(value)); }

inline QString ITrueConfCallX::XCommandLine() const
{
    QVariant qax_result = property("XCommandLine");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void ITrueConfCallX::SetXCommandLine(const QString& value){ setProperty("XCommandLine", QVariant(value)); }

inline void ITrueConfCallX::XAddSlide(const QString& imgPath)
{
    void *_a[] = {0, (void*)&imgPath};
    qt_metacall(QMetaObject::InvokeMetaMethod, 13, _a);
}

inline uint ITrueConfCallX::XAddSlidesDialog()
{
    uint qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 14, _a);
    return qax_result;
}

inline bool ITrueConfCallX::XCheckForEvent(const QString& notificationData, const QString& eventName)
{
    bool qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&notificationData, (void*)&eventName};
    qt_metacall(QMetaObject::InvokeMetaMethod, 15, _a);
    return qax_result;
}

inline void ITrueConfCallX::XDeselectCamera()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 16, _a);
}

inline void ITrueConfCallX::XDeselectMic()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 17, _a);
}

inline void ITrueConfCallX::XDeselectSpeaker()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 18, _a);
}

inline void ITrueConfCallX::XEncryptedLogin(const QString& login, const QString& password, bool encryptPassword)
{
    void *_a[] = {0, (void*)&login, (void*)&password, (void*)&encryptPassword};
    qt_metacall(QMetaObject::InvokeMetaMethod, 19, _a);
}

inline void ITrueConfCallX::XExecuteCommand(const QString& cmd)
{
    void *_a[] = {0, (void*)&cmd};
    qt_metacall(QMetaObject::InvokeMetaMethod, 20, _a);
}

inline bool ITrueConfCallX::XFileAccept(int fileId)
{
    bool qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&fileId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 21, _a);
    return qax_result;
}

inline bool ITrueConfCallX::XFileDelete(int fileId)
{
    bool qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&fileId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 22, _a);
    return qax_result;
}

inline bool ITrueConfCallX::XFileReject(int fileId)
{
    bool qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&fileId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 23, _a);
    return qax_result;
}

inline int ITrueConfCallX::XFileSend(const QString& peerId, const QString& filePath, const QString& fileCaption)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&peerId, (void*)&filePath, (void*)&fileCaption};
    qt_metacall(QMetaObject::InvokeMetaMethod, 24, _a);
    return qax_result;
}

inline bool ITrueConfCallX::XFileSendAbort(int fileId)
{
    bool qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&fileId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 25, _a);
    return qax_result;
}

inline int ITrueConfCallX::XFileSendToConference(const QString& filePath, const QString& fileCaption)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&filePath, (void*)&fileCaption};
    qt_metacall(QMetaObject::InvokeMetaMethod, 26, _a);
    return qax_result;
}

inline bool ITrueConfCallX::XFileStatsInfo(int fileId, int& size, int& downloaded, int& uploaded, int& u_speed, int& d_speed, int& peers)
{
    bool qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&fileId, (void*)&size, (void*)&downloaded, (void*)&uploaded, (void*)&u_speed, (void*)&d_speed, (void*)&peers};
    qt_metacall(QMetaObject::InvokeMetaMethod, 27, _a);
    return qax_result;
}

inline bool ITrueConfCallX::XFileTransferAvailable()
{
    bool qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 28, _a);
    return qax_result;
}

inline void ITrueConfCallX::XForceRestart()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 29, _a);
}

inline int ITrueConfCallX::XGetCallXProcessId()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 30, _a);
    return qax_result;
}

inline QString ITrueConfCallX::XGetCameraByIndex(int cameraIdx)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&cameraIdx};
    qt_metacall(QMetaObject::InvokeMetaMethod, 31, _a);
    return qax_result;
}

inline int ITrueConfCallX::XGetCameraCount()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 32, _a);
    return qax_result;
}

inline QString ITrueConfCallX::XGetCameraList()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 33, _a);
    return qax_result;
}

inline QString ITrueConfCallX::XGetFileDownloadPath(int fileId)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&fileId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 34, _a);
    return qax_result;
}

inline QString ITrueConfCallX::XGetFileHashById(int fileId)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&fileId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 35, _a);
    return qax_result;
}

inline int ITrueConfCallX::XGetFileIdByHash(const QString& hash)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&hash};
    qt_metacall(QMetaObject::InvokeMetaMethod, 36, _a);
    return qax_result;
}

inline int ITrueConfCallX::XGetFileSendStatus(int id)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&id};
    qt_metacall(QMetaObject::InvokeMetaMethod, 37, _a);
    return qax_result;
}

inline QString ITrueConfCallX::XGetFileTransferList()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 38, _a);
    return qax_result;
}

inline uint ITrueConfCallX::XGetHandle()
{
    uint qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 39, _a);
    return qax_result;
}

inline QString ITrueConfCallX::XGetMicByIndex(int microphoneIdx)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&microphoneIdx};
    qt_metacall(QMetaObject::InvokeMetaMethod, 40, _a);
    return qax_result;
}

inline int ITrueConfCallX::XGetMicCount()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 41, _a);
    return qax_result;
}

inline QString ITrueConfCallX::XGetMicList()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 42, _a);
    return qax_result;
}

inline QString ITrueConfCallX::XGetSpeakerByIndex(int speakerIdx)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&speakerIdx};
    qt_metacall(QMetaObject::InvokeMetaMethod, 43, _a);
    return qax_result;
}

inline int ITrueConfCallX::XGetSpeakerCount()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 44, _a);
    return qax_result;
}

inline QString ITrueConfCallX::XGetSpeakerList()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 45, _a);
    return qax_result;
}

inline void ITrueConfCallX::XHangUpForAll()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 46, _a);
}

inline int ITrueConfCallX::XPrintPdf(const QString& filePath)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&filePath};
    qt_metacall(QMetaObject::InvokeMetaMethod, 47, _a);
    return qax_result;
}

inline int ITrueConfCallX::XRemotePrintPdf(const QString& peerId, int fileId)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&peerId, (void*)&fileId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 48, _a);
    return qax_result;
}

inline void ITrueConfCallX::XRemoveSlide(int imgIdx)
{
    void *_a[] = {0, (void*)&imgIdx};
    qt_metacall(QMetaObject::InvokeMetaMethod, 49, _a);
}

inline void ITrueConfCallX::XRestart()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 50, _a);
}

inline void ITrueConfCallX::XSelectCamera(const QString& cameraName)
{
    void *_a[] = {0, (void*)&cameraName};
    qt_metacall(QMetaObject::InvokeMetaMethod, 51, _a);
}

inline void ITrueConfCallX::XSelectMicByIndex(int microphoneIdx)
{
    void *_a[] = {0, (void*)&microphoneIdx};
    qt_metacall(QMetaObject::InvokeMetaMethod, 52, _a);
}

inline void ITrueConfCallX::XSelectSpeakerByIndex(int speakerIdx)
{
    void *_a[] = {0, (void*)&speakerIdx};
    qt_metacall(QMetaObject::InvokeMetaMethod, 53, _a);
}

inline void ITrueConfCallX::XSetBackgroundImage(const QString& imgPath)
{
    void *_a[] = {0, (void*)&imgPath};
    qt_metacall(QMetaObject::InvokeMetaMethod, 54, _a);
}

inline void ITrueConfCallX::XSetCameraByIndex(int cameraIdx)
{
    void *_a[] = {0, (void*)&cameraIdx};
    qt_metacall(QMetaObject::InvokeMetaMethod, 55, _a);
}

inline void ITrueConfCallX::XStartPictureBroadcast(const QString& imgPath)
{
    void *_a[] = {0, (void*)&imgPath};
    qt_metacall(QMetaObject::InvokeMetaMethod, 56, _a);
}

inline void ITrueConfCallX::XStopPictureBroadcast()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 57, _a);
}

inline void ITrueConfCallX::accept()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 58, _a);
}

inline void ITrueConfCallX::acceptPeer(const QString& peerId)
{
    void *_a[] = {0, (void*)&peerId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 59, _a);
}

inline void ITrueConfCallX::acceptPodiumInvite()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 60, _a);
}

inline void ITrueConfCallX::acceptPodiumRequest()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 61, _a);
}

inline void ITrueConfCallX::acceptPodiumRequest2(const QString& peerId)
{
    void *_a[] = {0, (void*)&peerId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 62, _a);
}

inline void ITrueConfCallX::activateLicense(const QString& licenseKey)
{
    void *_a[] = {0, (void*)&licenseKey};
    qt_metacall(QMetaObject::InvokeMetaMethod, 63, _a);
}

inline void ITrueConfCallX::addContactToAbook(const QString& callId, const QString& displayName)
{
    void *_a[] = {0, (void*)&callId, (void*)&displayName};
    qt_metacall(QMetaObject::InvokeMetaMethod, 64, _a);
}

inline QString ITrueConfCallX::addToAbook(const QString& peerId, const QString& displayName)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&peerId, (void*)&displayName};
    qt_metacall(QMetaObject::InvokeMetaMethod, 65, _a);
    return qax_result;
}

inline QString ITrueConfCallX::addToGroup(int groupId, const QString& peerId)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&groupId, (void*)&peerId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 66, _a);
    return qax_result;
}

inline void ITrueConfCallX::allowRecord()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 67, _a);
}

inline void ITrueConfCallX::allowRecord2(const QString& peerId)
{
    void *_a[] = {0, (void*)&peerId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 68, _a);
}

inline void ITrueConfCallX::appUpdate()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 69, _a);
}

inline QString ITrueConfCallX::block(const QString& peerId)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&peerId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 70, _a);
    return qax_result;
}

inline void ITrueConfCallX::call(const QString& peerId)
{
    void *_a[] = {0, (void*)&peerId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 71, _a);
}

inline void ITrueConfCallX::changeVideoMatrix(const QString& jsonMatrix)
{
    void *_a[] = {0, (void*)&jsonMatrix};
    qt_metacall(QMetaObject::InvokeMetaMethod, 72, _a);
}

inline QString ITrueConfCallX::chatClear(const QString& chatId)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&chatId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 73, _a);
    return qax_result;
}

inline void ITrueConfCallX::clearSlides()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 74, _a);
}

inline void ITrueConfCallX::connectToServer(const QString& serverStr)
{
    void *_a[] = {0, (void*)&serverStr};
    qt_metacall(QMetaObject::InvokeMetaMethod, 75, _a);
}

inline void ITrueConfCallX::createConference(const QString& confName, const QString& type, bool autoAccept, const QString& users)
{
    void *_a[] = {0, (void*)&confName, (void*)&type, (void*)&autoAccept, (void*)&users};
    qt_metacall(QMetaObject::InvokeMetaMethod, 76, _a);
}

inline QString ITrueConfCallX::createGroup(const QString& name)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&name};
    qt_metacall(QMetaObject::InvokeMetaMethod, 77, _a);
    return qax_result;
}

inline void ITrueConfCallX::extendUidTtl()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 78, _a);
}

inline void ITrueConfCallX::firstSlide()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 79, _a);
}

inline void ITrueConfCallX::forbidRecord()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 80, _a);
}

inline void ITrueConfCallX::forbidRecord2(const QString& peerId)
{
    void *_a[] = {0, (void*)&peerId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 81, _a);
}

inline void ITrueConfCallX::getAbook()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 82, _a);
}

inline void ITrueConfCallX::getAppState()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 83, _a);
}

inline void ITrueConfCallX::getAudioMute()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 84, _a);
}

inline QString ITrueConfCallX::getBanList()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 85, _a);
    return qax_result;
}

inline QString ITrueConfCallX::getCallHistory(int count)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&count};
    qt_metacall(QMetaObject::InvokeMetaMethod, 86, _a);
    return qax_result;
}

inline QString ITrueConfCallX::getChatLastMessages(const QString& chatId, int count)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&chatId, (void*)&count};
    qt_metacall(QMetaObject::InvokeMetaMethod, 87, _a);
    return qax_result;
}

inline void ITrueConfCallX::getContactDetails(const QString& peerId)
{
    void *_a[] = {0, (void*)&peerId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 88, _a);
}

inline void ITrueConfCallX::getDisplayNameById(const QString& peerId)
{
    void *_a[] = {0, (void*)&peerId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 89, _a);
}

inline QString ITrueConfCallX::getGroups()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 90, _a);
    return qax_result;
}

inline void ITrueConfCallX::getHardware()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 91, _a);
}

inline void ITrueConfCallX::getHardwareKey()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 92, _a);
}

inline void ITrueConfCallX::getIdListRequestInvite()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 93, _a);
}

inline void ITrueConfCallX::getLicenseType()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 94, _a);
}

inline QString ITrueConfCallX::getListOfChats()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 95, _a);
    return qax_result;
}

inline void ITrueConfCallX::getMaxConfTitleLength()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 96, _a);
}

inline void ITrueConfCallX::getMicMute()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 97, _a);
}

inline void ITrueConfCallX::getModes()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 98, _a);
}

inline void ITrueConfCallX::getMonitorsInfo()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 99, _a);
}

inline QString ITrueConfCallX::getParticipantsList()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 100, _a);
    return qax_result;
}

inline void ITrueConfCallX::getSelfieBroadcast()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 101, _a);
}

inline void ITrueConfCallX::getSettings()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 102, _a);
}

inline void ITrueConfCallX::getSlideShowInfo()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 103, _a);
}

inline void ITrueConfCallX::getSystemInfo()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 104, _a);
}

inline void ITrueConfCallX::getVideoMatrix()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 105, _a);
}

inline void ITrueConfCallX::getVideoMute()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 106, _a);
}

inline void ITrueConfCallX::gotoPodium()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 107, _a);
}

inline void ITrueConfCallX::hangUp()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 108, _a);
}

inline void ITrueConfCallX::hangUp2(bool forAll)
{
    void *_a[] = {0, (void*)&forAll};
    qt_metacall(QMetaObject::InvokeMetaMethod, 109, _a);
}

inline void ITrueConfCallX::inviteToConference(const QString& peerId)
{
    void *_a[] = {0, (void*)&peerId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 110, _a);
}

inline void ITrueConfCallX::inviteToPodium(const QString& peerId)
{
    void *_a[] = {0, (void*)&peerId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 111, _a);
}

inline void ITrueConfCallX::lastSlide()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 112, _a);
}

inline void ITrueConfCallX::leavePodium()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 113, _a);
}

inline void ITrueConfCallX::login(const QString& login, const QString& password)
{
    void *_a[] = {0, (void*)&login, (void*)&password};
    qt_metacall(QMetaObject::InvokeMetaMethod, 114, _a);
}

inline void ITrueConfCallX::logout()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 115, _a);
}

inline void ITrueConfCallX::moveSlideDown(int slideIdx)
{
    void *_a[] = {0, (void*)&slideIdx};
    qt_metacall(QMetaObject::InvokeMetaMethod, 116, _a);
}

inline void ITrueConfCallX::moveSlideUp(int slideIdx)
{
    void *_a[] = {0, (void*)&slideIdx};
    qt_metacall(QMetaObject::InvokeMetaMethod, 117, _a);
}

inline void ITrueConfCallX::nextSlide()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 118, _a);
}

inline void ITrueConfCallX::prevSlide()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 119, _a);
}

inline void ITrueConfCallX::ptzDown()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 120, _a);
}

inline void ITrueConfCallX::ptzLeft()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 121, _a);
}

inline void ITrueConfCallX::ptzRight()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 122, _a);
}

inline void ITrueConfCallX::ptzStop()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 123, _a);
}

inline void ITrueConfCallX::ptzUp()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 124, _a);
}

inline void ITrueConfCallX::ptzZoomIn()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 125, _a);
}

inline void ITrueConfCallX::ptzZoomOut()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 126, _a);
}

inline void ITrueConfCallX::reject()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 127, _a);
}

inline void ITrueConfCallX::rejectInvitationToPodium()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 128, _a);
}

inline void ITrueConfCallX::rejectPeer(const QString& peerId)
{
    void *_a[] = {0, (void*)&peerId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 129, _a);
}

inline void ITrueConfCallX::rejectRequestToPodium()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 130, _a);
}

inline void ITrueConfCallX::rejectRequestToPodium2(const QString& peerId)
{
    void *_a[] = {0, (void*)&peerId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 131, _a);
}

inline void ITrueConfCallX::removeContactFromAbook(const QString& callId)
{
    void *_a[] = {0, (void*)&callId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 132, _a);
}

inline QString ITrueConfCallX::removeFromAbook(const QString& peerId)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&peerId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 133, _a);
    return qax_result;
}

inline QString ITrueConfCallX::removeFromGroup(int groupId, const QString& peerId)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&groupId, (void*)&peerId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 134, _a);
    return qax_result;
}

inline void ITrueConfCallX::removeFromPodium(const QString& peerId)
{
    void *_a[] = {0, (void*)&peerId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 135, _a);
}

inline QString ITrueConfCallX::removeGroup(int groupId)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&groupId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 136, _a);
    return qax_result;
}

inline void ITrueConfCallX::removePeer(const QString& peerId)
{
    void *_a[] = {0, (void*)&peerId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 137, _a);
}

inline QString ITrueConfCallX::renameGroup(int groupId, const QString& newGroupName)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&groupId, (void*)&newGroupName};
    qt_metacall(QMetaObject::InvokeMetaMethod, 138, _a);
    return qax_result;
}

inline QString ITrueConfCallX::renameInAbook(const QString& peerId, const QString& newDisplayName)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&peerId, (void*)&newDisplayName};
    qt_metacall(QMetaObject::InvokeMetaMethod, 139, _a);
    return qax_result;
}

inline void ITrueConfCallX::sendCommand(const QString& peerId, const QString& cmd)
{
    void *_a[] = {0, (void*)&peerId, (void*)&cmd};
    qt_metacall(QMetaObject::InvokeMetaMethod, 140, _a);
}

inline QString ITrueConfCallX::sendGroupMessage(const QString& message)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&message};
    qt_metacall(QMetaObject::InvokeMetaMethod, 141, _a);
    return qax_result;
}

inline QString ITrueConfCallX::sendMessage(const QString& peerId, const QString& message)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&peerId, (void*)&message};
    qt_metacall(QMetaObject::InvokeMetaMethod, 142, _a);
    return qax_result;
}

inline void ITrueConfCallX::setAudioMute(bool mute)
{
    void *_a[] = {0, (void*)&mute};
    qt_metacall(QMetaObject::InvokeMetaMethod, 143, _a);
}

inline void ITrueConfCallX::setHardware(const QString& hardwareInJson)
{
    void *_a[] = {0, (void*)&hardwareInJson};
    qt_metacall(QMetaObject::InvokeMetaMethod, 144, _a);
}

inline QString ITrueConfCallX::setLastCallsViewed()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 145, _a);
    return qax_result;
}

inline void ITrueConfCallX::setMicMute(bool mute)
{
    void *_a[] = {0, (void*)&mute};
    qt_metacall(QMetaObject::InvokeMetaMethod, 146, _a);
}

inline void ITrueConfCallX::setModes(const QString& pin, const QString& mode)
{
    void *_a[] = {0, (void*)&pin, (void*)&mode};
    qt_metacall(QMetaObject::InvokeMetaMethod, 147, _a);
}

inline void ITrueConfCallX::setSelfieBroadcast(const QString& paramsInJSON)
{
    void *_a[] = {0, (void*)&paramsInJSON};
    qt_metacall(QMetaObject::InvokeMetaMethod, 148, _a);
}

inline void ITrueConfCallX::setSettings(const QString& settingsInJson)
{
    void *_a[] = {0, (void*)&settingsInJson};
    qt_metacall(QMetaObject::InvokeMetaMethod, 149, _a);
}

inline void ITrueConfCallX::setVideoMute(bool mute)
{
    void *_a[] = {0, (void*)&mute};
    qt_metacall(QMetaObject::InvokeMetaMethod, 150, _a);
}

inline void ITrueConfCallX::showSlide(int slideIdx)
{
    void *_a[] = {0, (void*)&slideIdx};
    qt_metacall(QMetaObject::InvokeMetaMethod, 151, _a);
}

inline void ITrueConfCallX::shutdown()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 152, _a);
}

inline void ITrueConfCallX::shutdown2(bool forAll)
{
    void *_a[] = {0, (void*)&forAll};
    qt_metacall(QMetaObject::InvokeMetaMethod, 153, _a);
}

inline void ITrueConfCallX::startAudioRemark()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 154, _a);
}

inline void ITrueConfCallX::startScreenCapture(const QString& id)
{
    void *_a[] = {0, (void*)&id};
    qt_metacall(QMetaObject::InvokeMetaMethod, 155, _a);
}

inline void ITrueConfCallX::startSlideShow(const QString& slideShowName)
{
    void *_a[] = {0, (void*)&slideShowName};
    qt_metacall(QMetaObject::InvokeMetaMethod, 156, _a);
}

inline void ITrueConfCallX::stopScreenCapture()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 157, _a);
}

inline void ITrueConfCallX::stopSlideShow()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 158, _a);
}

inline void ITrueConfCallX::switchVideoStream(const QString& peerId, bool mainCamera)
{
    void *_a[] = {0, (void*)&peerId, (void*)&mainCamera};
    qt_metacall(QMetaObject::InvokeMetaMethod, 159, _a);
}

inline void ITrueConfCallX::takePicture(const QString& outputFileName)
{
    void *_a[] = {0, (void*)&outputFileName};
    qt_metacall(QMetaObject::InvokeMetaMethod, 160, _a);
}

inline QString ITrueConfCallX::testAudioCapturerStart()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 161, _a);
    return qax_result;
}

inline QString ITrueConfCallX::testAudioCapturerStop()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 162, _a);
    return qax_result;
}

inline QString ITrueConfCallX::testAudioRenderer()
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 163, _a);
    return qax_result;
}

inline QString ITrueConfCallX::toneDial(const QString& symbol)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&symbol};
    qt_metacall(QMetaObject::InvokeMetaMethod, 164, _a);
    return qax_result;
}

inline void ITrueConfCallX::turnRemoteCamera(const QString& peerId, bool on)
{
    void *_a[] = {0, (void*)&peerId, (void*)&on};
    qt_metacall(QMetaObject::InvokeMetaMethod, 165, _a);
}

inline void ITrueConfCallX::turnRemoteMic(const QString& peerId, bool on)
{
    void *_a[] = {0, (void*)&peerId, (void*)&on};
    qt_metacall(QMetaObject::InvokeMetaMethod, 166, _a);
}

inline QString ITrueConfCallX::unblock(const QString& peerId)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&peerId};
    qt_metacall(QMetaObject::InvokeMetaMethod, 167, _a);
    return qax_result;
}



#endif

}

QT_BEGIN_NAMESPACE

namespace QtMetaTypePrivate {
template<>
struct QMetaTypeFunctionHelper<TrueConf_CallXLib::TrueConfCallX, /* Accepted */ true> {
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<TrueConf_CallXLib::TrueConfCallX*>(t)->TrueConf_CallXLib::TrueConfCallX::~TrueConfCallX();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) TrueConf_CallXLib::TrueConfCallX;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const TrueConf_CallXLib::TrueConfCallX*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<TrueConf_CallXLib::TrueConfCallX*>(t); }
#endif // QT_NO_DATASTREAM
};

template<>
struct QMetaTypeFunctionHelper<TrueConf_CallXLib::ITrueConfCallX, /* Accepted */ true> {
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<TrueConf_CallXLib::ITrueConfCallX*>(t)->TrueConf_CallXLib::ITrueConfCallX::~ITrueConfCallX();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) TrueConf_CallXLib::ITrueConfCallX;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const TrueConf_CallXLib::ITrueConfCallX*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<TrueConf_CallXLib::ITrueConfCallX*>(t); }
#endif // QT_NO_DATASTREAM
};

} // namespace QtMetaTypePrivate
QT_END_NAMESPACE

#endif

